apiVersion: v1
kind: Service
metadata:
  name: translator-svc
  namespace: translator
  labels:
    app: translator
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007
    protocol: TCP
  selector:
    app: translator